/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    gebruikers: GebruikerAuthOperations;
  };
  blocks: {};
  collections: {
    gebruikers: Gebruiker;
    diensten: Diensten;
    afspraken: Afspraken;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    gebruikers: GebruikersSelect<false> | GebruikersSelect<true>;
    diensten: DienstenSelect<false> | DienstenSelect<true>;
    afspraken: AfsprakenSelect<false> | AfsprakenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    beschikbaarheid: Beschikbaarheid;
  };
  globalsSelect: {
    beschikbaarheid: BeschikbaarheidSelect<false> | BeschikbaarheidSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Gebruiker;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface GebruikerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers".
 */
export interface Gebruiker {
  id: number;
  naam?: string | null;
  rol: 'admin' | 'medewerker';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'gebruikers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten".
 */
export interface Diensten {
  id: number;
  naam: string;
  /**
   * URL-naam, bijv. paspoort-aanvragen
   */
  slug: string;
  beschrijving?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benodigdeDocumenten?:
    | {
        document: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bijv. '4 tot 6 weken'
   */
  doorlooptijd?: string | null;
  zichtbaar?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "afspraken".
 */
export interface Afspraken {
  id: number;
  naam: string;
  email: string;
  telefoon?: string | null;
  dienst: number | Diensten;
  datum: string;
  /**
   * Bijv. 09:30
   */
  tijdslot: string;
  status: 'aangevraagd' | 'bevestigd' | 'afgehandeld' | 'geannuleerd';
  /**
   * Wordt automatisch gegenereerd
   */
  referentie?: string | null;
  notities?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'gebruikers';
        value: number | Gebruiker;
      } | null)
    | ({
        relationTo: 'diensten';
        value: number | Diensten;
      } | null)
    | ({
        relationTo: 'afspraken';
        value: number | Afspraken;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers_select".
 */
export interface GebruikersSelect<T extends boolean = true> {
  naam?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten_select".
 */
export interface DienstenSelect<T extends boolean = true> {
  naam?: T;
  slug?: T;
  beschrijving?: T;
  benodigdeDocumenten?:
    | T
    | {
        document?: T;
        id?: T;
      };
  doorlooptijd?: T;
  zichtbaar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "afspraken_select".
 */
export interface AfsprakenSelect<T extends boolean = true> {
  naam?: T;
  email?: T;
  telefoon?: T;
  dienst?: T;
  datum?: T;
  tijdslot?: T;
  status?: T;
  referentie?: T;
  notities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beschikbaarheid".
 */
export interface Beschikbaarheid {
  id: number;
  openingsdagen?: {
    maandag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
    dinsdag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
    woensdag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
    donderdag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
    vrijdag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
    zaterdag?: {
      open?: boolean | null;
      tijdsloten?:
        | {
            /**
             * 24-uurs, bijv. 09:30
             */
            tijd: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  geblokkeerdeDatums?:
    | {
        datum: string;
        /**
         * Bijv. 'Onafhankelijkheidsdag'
         */
        omschrijving?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beschikbaarheid_select".
 */
export interface BeschikbaarheidSelect<T extends boolean = true> {
  openingsdagen?:
    | T
    | {
        maandag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
        dinsdag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
        woensdag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
        donderdag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
        vrijdag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
        zaterdag?:
          | T
          | {
              open?: T;
              tijdsloten?:
                | T
                | {
                    tijd?: T;
                    id?: T;
                  };
            };
      };
  geblokkeerdeDatums?:
    | T
    | {
        datum?: T;
        omschrijving?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}